import { ObjectSchema } from "realm";

export const ownerSchema: ObjectSchema = {
  name: "owner",
  primaryKey: "id",
  properties: {
    bio: "string?",
    url: "string?",
    blog: "string?",
    name: "string?",
    type: "string?",
    email: "string?",
    login: "string?",
    followers: "int?",
    following: "int?",
    company: "string?",
    node_id: "string?",
    site_admin: "bool?",
    location: "string?",
    html_url: "string?",
    gists_url: "string?",
    public_gists: "int?",
    public_repos: "int?",
    repos_url: "string?",
    events_url: "string?",
    avatar_url: "string?",
    created_at: "string?",
    updated_at: "string?",
    gravatar_id: "string?",
    starred_url: "string?",
    followers_url: "string?",
    following_url: "string?",
    twitter_username: "string?",
    organizations_url: "string?",
    subscriptions_url: "string?",
    received_events_url: "string?",
    id: { type: "int?", indexed: true },
  },
};
