import { ObjectSchema } from "realm";

export const ownerEmbedded: ObjectSchema = {
  embedded: true,
  name: "owner-embedded",
  properties: {
    url: "string?",
    type: "string?",
    login: "string?",
    node_id: "string?",
    html_url: "string?",
    site_admin: "bool?",
    gists_url: "string?",
    repos_url: "string?",
    avatar_url: "string?",
    events_url: "string?",
    gravatar_id: "string?",
    starred_url: "string?",
    followers_url: "string?",
    following_url: "string?",
    organizations_url: "string?",
    subscriptions_url: "string?",
    received_events_url: "string?",
    id: { type: "int?", indexed: true },
  },
};

export const repositorySchema: ObjectSchema = {
  primaryKey: "id",
  name: "repository",
  properties: {
    size: "int?",
    fork: "bool?",
    forks: "int?",
    url: "string?",
    name: "string?",
    private: "bool?",
    watchers: "int?",
    has_wiki: "bool?",
    archived: "bool?",
    disabled: "bool?",
    git_url: "string?",
    has_pages: "bool?",
    node_id: "string?",
    ssh_url: "string?",
    svn_url: "string?",
    forks_count: "int?",
    keys_url: "string?",
    has_issues: "bool?",
    language: "string?",
    open_issues: "int?",
    tags_url: "string?",
    html_url: "string?",
    blobs_url: "string?",
    clone_url: "string?",
    forks_url: "string?",
    full_name: "string?",
    pulls_url: "string?",
    pushed_at: "string?",
    teams_url: "string?",
    trees_url: "string?",
    hooks_url: "string?",
    is_template: "bool?",
    created_at: "string?",
    events_url: "string?",
    issues_url: "string?",
    has_projects: "bool?",
    labels_url: "string?",
    merges_url: "string?",
    updated_at: "string?",
    visibility: "string?",
    allow_forking: "bool?",
    archive_url: "string?",
    commits_url: "string?",
    compare_url: "string?",
    description: "string?",
    has_downloads: "bool?",
    watchers_count: "int?",
    comments_url: "string?",
    contents_url: "string?",
    branches_url: "string?",
    git_refs_url: "string?",
    releases_url: "string?",
    statuses_url: "string?",
    git_tags_url: "string?",
    stargazers_count: "int?",
    has_discussions: "bool?",
    assignees_url: "string?",
    downloads_url: "string?",
    languages_url: "string?",
    milestones_url: "string?",
    open_issues_count: "int?",
    stargazers_url: "string?",
    default_branch: "string?",
    subscribers_url: "string?",
    deployments_url: "string?",
    git_commits_url: "string?",
    subscription_url: "string?",
    issue_events_url: "string?",
    contributors_url: "string?",
    collaborators_url: "string?",
    issue_comment_url: "string?",
    notifications_url: "string?",
    id: { type: "int?", indexed: true },
    web_commit_signoff_required: "bool?",
    owner: { type: ownerEmbedded.name, default: {} },
  },
};
